### PR TITLE
fix: use eslint-config-airbnb-base by default

### LINKED ISSUE #87: Bug: @eslint/config init installs wrong dependencies
### Environment

Node version: 20.11.1
npm version: 10.2.4
Local ESLint version: ^8.57.0
Global ESLint version: 8.57.0
Operating System: Windows 10

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

I was initializing eslint for my node backend and I used the npm init @eslint/config command to initiate the config dialogue.
I selected the following configurations:

image

Then it told me what dependecies that configuration needed and I installed them:

image

The bug that I found was that it still installed the following dependencies eventhough in the config dialogue I told it that my project was using node so there shouldnt be no need for the react and jsx plugins.

image

</details>

### What did you expect to happen?

I expected it to only install the needed dependencies and nothing else

### What actually happened?

It installed  
- eslint-plugin-jsx-a11y
- eslint-plugin-react
- eslint-plugin-react-hooks

eventhough I specified that my code ran on Node and not on Browser

### Link to Minimal Reproducible Example

the minimal reproducible example is already in the "what did you do " section

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by aladdin-add**
eslint-congif-airbnb is only used for react.
fixes #87

### CODE REVIEW

File: lib/config-generator.js [hunk 1]
```diff
@@ -133,6 +134,15 @@ export class ConfigGenerator {
         const isESMModule = isPackageTypeModule(this.packageJsonPath);
 
         this.result.configFilename = isESMModule ? "eslint.config.js" : "eslint.config.mjs";
+        this.answers.styleguide = typeof this.answers.styleguide === "string"
```
Comment (mdjermanovic) [inline lib/config-generator.js:137]: In which cases `this.answers.styleguide` can be a string value?

Comment (aladdin-add) [reply lib/config-generator.js:137]: More for the future: none of the style guides in the list now support flat configs, so you have to use:

```js
"styleguide": { "packageName": "eslint-config-airbnb", "type": "eslintrc"}
```
But when a certain support is available it can be written as:
```js
 "styleguide": "eslint-config-airbnb"
```

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! I can confirm that this matches the previous (v0.4.6) behavior in terms of which configuration combinations are used for which combinations of answers.
