### PR TITLE
fix: use @eslint/compat to fix eslint v9 + react plugin

### LINKED ISSUE #106: Init wizard installs old version
### Environment

Node version: v21.7.3
npm version: 10.5.2
Local ESLint version: v9.1.1
Operating System: MacOS

### What parser are you using?

Default (Espree)

### What did you do?

$ npm init @eslint/config@latest
(accept defaults)

$ npx eslint --version

### What did you expect to happen?

v9.1.1

### What actually happened?

v8.57.0

### PR DESCRIPTION
**Pull request by aladdin-add**
fixes #106

1. use `eslint/compat` for react plugin.
2. use `--force` when installing dev deps.

the generated snapshots:
v8: https://github.com/eslint/create-config/blob/4517b301f2f46e4fdf367b03bd1d69f76813632a/tests/__snapshots__/syntax-esm-react-eslint8.x-javascript

v9:https://github.com/eslint/create-config/blob/4517b301f2f46e4fdf367b03bd1d69f76813632a/tests/__snapshots__/syntax-esm-react-eslint9.x-javascript

### CODE REVIEW

File: lib/config-generator.js [hunk 1]
```diff
@@ -68,7 +68,7 @@ export class ConfigGenerator {
                 message: "Which framework does your project use?",
                 initial: 0,
                 choices: [
-                    { message: "React", name: "react" },
+                    { message: "React (⚠️eslint v9 has not been officially supported.)", name: "react" },
```
Comment (aladdin-add) [inline lib/config-generator.js:71]: added a note, as it will output an warning when using `npm install --force`:

```bash
The config that you've selected requires the following dependencies:

eslint@^9.2.0, globals, @eslint/js, eslint-plugin-react, @eslint/compat
✔ Would you like to install them now? · No / Yes
✔ Which package manager do you want to use? · npm
☕️Installing...
npm WARN using --force Recommended protections disabled.
npm WARN idealTree Removing dependencies.eslint in favor of devDependencies.eslint
npm WARN idealTree Removing dependencies.globals in favor of devDependencies.globals
npm WARN idealTree Removing dependencies.@eslint/js in favor of devDependencies.@eslint/js
npm WARN idealTree Removing dependencies.eslint-plugin-react in favor of devDependencies.eslint-plugin-react
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: example@1.0.0
npm WARN Found: eslint@8.57.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm WARN   node_modules/@eslint-community/eslint-utils
npm WARN     @eslint-community/eslint-utils@"^4.2.0" from eslint@8.57.0
npm WARN   2 more (eslint-plugin-react, the root project)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^3 || ^4 || ^5 || ^6 || ^7 || ^8" from eslint-plugin-react@7.34.1
npm WARN node_modules/eslint-plugin-react
npm WARN   dev eslint-plugin-react@"*" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: eslint-plugin-react@7.34.1
npm WARN Found: eslint@9.2.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"^9.2.0" from the root project
npm WARN   1 more (@eslint-community/eslint-utils)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^3 || ^4 || ^5 || ^6 || ^7 || ^8" from eslint-plugin-react@7.34.1
npm WARN node_modules/eslint-plugin-react
npm WARN   dev eslint-plugin-react@"*" from the root project
npm WARN 
npm WARN Conflicting peer dependency: eslint@8.57.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^3 || ^4 || ^5 || ^6 || ^7 || ^8" from eslint-plugin-react@7.34.1
npm WARN   node_modules/eslint-plugin-react
npm WARN     dev eslint-plugin-react@"*" from the root project

added 5 packages, removed 3 packages, and changed 19 packages in 30s

36 packages are looking for funding
  run `npm fund` for details
```

Comment (nzakas) [reply lib/config-generator.js:71]: I think this will confuse people. What if we just kept this as "React", and then, if it is selected, output another message:

> The React plugin doesn't officially support ESLint v9 yet. What would you like to do?
>
> - Install ESLint v9.x with compatibility utilities
> - Install ESLint v8.x

Comment (aladdin-add) [reply lib/config-generator.js:71]: 👍 sounds good, will make a change later.
