### PR TITLE
fix: exit gracefully on `Ctrl+C`

### LINKED ISSUE #192: Aborting with Ctrl+C causes crash
### What did you do?

At the first prompt (“What do you want to lint?”), pressed Ctrl+C.

### What did you expect to happen?

The process exits gracefully

### What actually happened?

The process crashes with a stack trace:

```
× What do you want to lint? · No items were selected
node:internal/readline/interface:568
      throw new ERR_USE_AFTER_CLOSE('readline');
            ^

Error [ERR_USE_AFTER_CLOSE]: readline was closed
    at Interface.pause (node:internal/readline/interface:568:13)
    at MultiSelect.off [as stop] ()
    ...
```

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by Pixel998**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/eslint/.github/blob/master/CONTRIBUTING.md).

#### What is the purpose of this pull request?

Prevent a crash when pressing `Ctrl+C` by exiting gracefully.

#### What changes did you make? (Give an overview)

Added an `uncaughtException` handler that catches `ERR_USE_AFTER_CLOSE` and calls `process.exit(1)`, rethrowing other errors.

#### Related Issues

Fixes #192

### CODE REVIEW

File: bin/create-config.js [hunk 1]
```diff
@@ -15,6 +15,15 @@ const pkg = JSON.parse(await fs.readFile(new URL("../package.json", import.meta.
 
 info(`${pkg.name}: v${pkg.version}\n`);
 
+process.on("uncaughtException", error => {
+    if (error instanceof Error && error.code === "ERR_USE_AFTER_CLOSE") {
+        // eslint-disable-next-line n/no-process-exit -- exit gracefully on Ctrl+C
+        process.exit(1);
```
Comment (aladdin-add) [inline bin/create-config.js:21]:
```bash
PS D:\repos\eslint-org\create-config\example> node ..\bin\create-config.js
@eslint/create-config: v1.10.0

√ What do you want to lint? · javascript
× How would you like to use ESLint? ·
```
Exiting directly doesn't seem like a good user experience. At the very least, we could output something like "Operation canceled"?

**Review by DMartens — APPROVED** [review]
Changes LGTM, thank you.
